import "./styles/globals.css";
import QueryClientProvider from "./queryClient";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<QueryClientProvider>{children}</QueryClientProvider>
			</body>
		</html>
	);
}
